//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FickleFrostbite.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public Activity()
        {
            this.Laps = new HashSet<Lap>();
        }
    
        public int ActivityId { get; set; }
        public string TcxActivityId { get; set; }
        public string Sport { get; set; }
    
        public virtual ICollection<Lap> Laps { get; set; }
    }
}
