//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FickleFrostbite.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatabaseVersion_Log
    {
        public System.DateTime LogTimestamp { get; set; }
        public string VersionNumber { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string SchemaUpdatedBy { get; set; }
    }
}
