//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FickleFrostbite.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trackpoint
    {
        public int TrackpointId { get; set; }
        public int LapId { get; set; }
        public System.DateTime Time { get; set; }
        public Nullable<decimal> LatitudeDegrees { get; set; }
        public Nullable<decimal> LongitudeDegrees { get; set; }
        public decimal AltitudeMeters { get; set; }
        public decimal DistanceMeters { get; set; }
        public Nullable<int> HeartRateBpm { get; set; }
    
        public virtual Lap Lap { get; set; }
    }
}
