#region Copyright
////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2015 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 16.10Release
// Tag = development-akw-16.10.00-0
////////////////////////////////////////////////////////////////////////////////

#endregion

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Text;
using System.IO;


namespace FickleFrostbite.FIT
{
   /// <summary>
   /// Implements the Video profile message.
   /// </summary>
   public class VideoMesg : Mesg
   {
      #region Fields
      #endregion

      #region Constructors
      public VideoMesg() : base(Profile.mesgs[Profile.VideoIndex])
      {
      }

      public VideoMesg(Mesg mesg) : base(mesg)
      {
      }
      #endregion // Constructors

      #region Methods
      ///<summary>
      /// Retrieves the Url field</summary>
      /// <returns>Returns byte[] representing the Url field</returns>
      public byte[] GetUrl()
      {
         return (byte[])GetFieldValue(0, 0, Fit.SubfieldIndexMainField);
      }

      
      ///<summary>
      /// Retrieves the Url field</summary>
      /// <returns>Returns String representing the Url field</returns>
      public String GetUrlAsString()
      {
         return Encoding.UTF8.GetString((byte[])GetFieldValue(0, 0, Fit.SubfieldIndexMainField));
      }
      

      
      ///<summary>
      /// Set Url field</summary>
      /// <returns>Returns String representing the Url field</returns>
      public void SetUrl(String url_)
      {
         SetFieldValue(0, 0, System.Text.Encoding.UTF8.GetBytes(url_), Fit.SubfieldIndexMainField);
      }
      

      /// <summary>
      /// Set Url field</summary>
      /// <param name="url_">field value to be set</param>
      public void SetUrl(byte[] url_)
      {
         SetFieldValue(0, 0, url_, Fit.SubfieldIndexMainField);
      }
      
      ///<summary>
      /// Retrieves the HostingProvider field</summary>
      /// <returns>Returns byte[] representing the HostingProvider field</returns>
      public byte[] GetHostingProvider()
      {
         return (byte[])GetFieldValue(1, 0, Fit.SubfieldIndexMainField);
      }

      
      ///<summary>
      /// Retrieves the HostingProvider field</summary>
      /// <returns>Returns String representing the HostingProvider field</returns>
      public String GetHostingProviderAsString()
      {
         return Encoding.UTF8.GetString((byte[])GetFieldValue(1, 0, Fit.SubfieldIndexMainField));
      }
      

      
      ///<summary>
      /// Set HostingProvider field</summary>
      /// <returns>Returns String representing the HostingProvider field</returns>
      public void SetHostingProvider(String hostingProvider_)
      {
         SetFieldValue(1, 0, System.Text.Encoding.UTF8.GetBytes(hostingProvider_), Fit.SubfieldIndexMainField);
      }
      

      /// <summary>
      /// Set HostingProvider field</summary>
      /// <param name="hostingProvider_">field value to be set</param>
      public void SetHostingProvider(byte[] hostingProvider_)
      {
         SetFieldValue(1, 0, hostingProvider_, Fit.SubfieldIndexMainField);
      }
      
      ///<summary>
      /// Retrieves the Duration field
      /// Units: ms
      /// Comment: Playback time of video</summary>
      /// <returns>Returns nullable uint representing the Duration field</returns>
      public uint? GetDuration()
      {
         return (uint?)GetFieldValue(2, 0, Fit.SubfieldIndexMainField);
      }

      

      

      /// <summary>
      /// Set Duration field
      /// Units: ms
      /// Comment: Playback time of video</summary>
      /// <param name="duration_">Nullable field value to be set</param>
      public void SetDuration(uint? duration_)
      {
         SetFieldValue(2, 0, duration_, Fit.SubfieldIndexMainField);
      }
      
      #endregion // Methods
   } // Class
} // namespace
